### ISSUE TITLE
Swaylock exits/crashes after some time

### ISSUE THREAD

**Issue by rfs613** [swaywm/swaylock#158]
Note: the symptoms here are similar to #126 however the crash seems to be different.

Symptom: after locking the screen via swayidle which calls swaylock... I return and find the screen is unlocked. The problem is intermittent, sometimes swaylock is running and prompts me for password, unlocks okay, etc. Other times it has crashed and I'm taken directly to desktop.

The error occurs several times per day, and analysis of the core files shows the same backtrace in each case:
```gdb
(gdb) bt
#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007fe974a868a4 in __GI_abort () at abort.c:79
#2  0x00007fe974ae0127 in __libc_message (action=<optimized out>, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007fe974ae7e1c in malloc_printerr (str=str@entry=0x7fe974bf4ec8 "malloc_consolidate(): unaligned fastbin chunk detected") at malloc.c:5389
#4  0x00007fe974ae8ec4 in malloc_consolidate (av=av@entry=0x7fe974c25a00 <main_arena>) at malloc.c:4509
#5  0x00007fe974aead73 in _int_malloc (av=av@entry=0x7fe974c25a00 <main_arena>, bytes=bytes@entry=1440) at malloc.c:3727
#6  0x00007fe974aec8a4 in __GI___libc_malloc (bytes=bytes@entry=1440) at malloc.c:3078
#7  0x00007fe974d41a3a in _cairo_default_context_create (target=0x56414abfd6a0) at cairo-default-context.c:1484
#8  0x000056414985ddd9 in create_buffer (format=0, height=1, width=1, buf=0x56414ac2eff0, shm=<optimized out>) at ../pool-buffer.c:94
#9  get_next_buffer (shm=<optimized out>, pool=<optimized out>, width=1, height=1) at ../pool-buffer.c:136
#10 0x000056414985df26 in render_frame (surface=0x56414ac2ef00) at ../render.c:105
#11 0x00007fe974237b10 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#12 0x00007fe9742370a3 in ffi_call (cif=cif@entry=0x7ffc6bde2050, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x0, 
    avalue=avalue@entry=0x7ffc6bde2120) at ../src/x86/ffi64.c:525
#13 0x00007fe974c468fe in wl_closure_invoke (closure=closure@entry=0x56414ac29840, target=<optimized out>, target@entry=0x56414abdcc10, 
    opcode=opcode@entry=0, data=<optimized out>, flags=<optimized out>) at src/connection.c:1018
#14 0x00007fe974c46fcb in dispatch_event (display=display@entry=0x56414abb21a0, queue=<optimized out>, queue=<optimized out>) at src/wayland-client.c:1445
#15 0x00007fe974c4719c in dispatch_queue (queue=0x56414abb2270, display=0x56414abb21a0) at src/wayland-client.c:1591
#16 wl_display_dispatch_queue_pending (display=display@entry=0x56414abb21a0, queue=queue@entry=0x56414abb2270) at src/wayland-client.c:1833
#17 0x00007fe974c48963 in wl_display_dispatch_queue (queue=<optimized out>, display=<optimized out>) at src/wayland-client.c:1809
#18 0x00007fe974c496ef in wl_display_roundtrip_queue (display=0x56414abb21a0, queue=0x56414abb2270) at src/wayland-client.c:1251
#19 0x00007fe974237b10 in ffi_call_unix64 () at ../src/x86/unix64.S:76
#20 0x00007fe9742370a3 in ffi_call (cif=cif@entry=0x7ffc6bde2430, fn=<optimized out>, rvalue=<optimized out>, rvalue@entry=0x0, 
    avalue=avalue@entry=0x7ffc6bde2500) at ../src/x86/ffi64.c:525
#21 0x00007fe974c468fe in wl_closure_invoke (closure=closure@entry=0x56414ac0f870, target=<optimized out>, target@entry=0x56414abb6340, 
    opcode=opcode@entry=0, data=<optimized out>, flags=<optimized out>) at src/connection.c:1018
#22 0x00007fe974c46fcb in dispatch_event (display=display@entry=0x56414abb21a0, queue=<optimized out>, queue=<optimized out>) at src/wayland-client.c:1445
#23 0x00007fe974c4719c in dispatch_queue (queue=0x56414abb2270, display=0x56414abb21a0) at src/wayland-client.c:1591
#24 wl_display_dispatch_queue_pending (display=0x56414abb21a0, queue=0x56414abb2270) at src/wayland-client.c:1833
#25 0x000056414985d944 in display_in (fd=<optimized out>, mask=<optimized out>, data=<optimized out>) at ../main.c:1080
#26 0x000056414985a8a6 in loop_poll (loop=0x56414aba4000) at ../loop.c:95
#27 main (argc=5, argv=0x7ffc6bde2838) at ../main.c:1235
```
which seems to suggest memory corruption has occurred.

The issue seems to have started happening after recent upgrade from Fedora 32 to 33. This included updates of:
- swaylock 1.5.3 to 1.5.4
- wlroots 0.10.1 to 0.11.0

and of course many more. I kept the same sway config through the update, and never encountered this problem previously.

**Comment by rfs613** [comment]
I am able to trigger the problem:
- run swaylock manually (from terminal)
- toggle dpms off/on using swaymsg (did this using SSH+tmux from remote host)

It only failed twice in at least 30 attempts. But here's what valgrind had to say (first failure occurred without valgrind):

```
$ valgrind swaylock                                                                                                                           
==16261== Memcheck, a memory error detector                                                                                                                    
==16261== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.                                                                                      
==16261== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info                                                                                   
==16261== Command: swaylock                                                                                                                                    
==16261==                              
==16261== Invalid write of size 1                                                                                                                              
==16261==    at 0x10F4F4: buffer_release (pool-buffer.c:62)                                                                                                    
==16261==    by 0x5461B0F: ffi_call_unix64 (unix64.S:76)                                                                                                       
==16261==    by 0x54610A2: ffi_call (ffi64.c:525)                              
==16261==    by 0x4A498FD: wl_closure_invoke.constprop.0 (connection.c:1018)                                                                                   
==16261==    by 0x4A49FCA: dispatch_event.isra.0 (wayland-client.c:1445)                                                                                       
==16261==    by 0x4A4A19B: UnknownInlinedFun (wayland-client.c:1591)                                                                                           
==16261==    by 0x4A4A19B: wl_display_dispatch_queue_pending (wayland-client.c:1833)
==16261==    by 0x4A4C6EE: wl_display_roundtrip_queue (wayland-client.c:1251)                                                                                  
==16261==    by 0x5461B0F: ffi_call_unix64 (unix64.S:76)                                                                                                       
==16261==    by 0x54610A2: ffi_call (ffi64.c:525)                                                                                                              
==16261==    by 0x4A498FD: wl_closure_invoke.constprop.0 (connection.c:1018)                                                                                   
==16261==    by 0x4A49FCA: dispatch_event.isra.0 (wayland-client.c:1445)                                                                                       
==16261==    by 0x4A4A19B: UnknownInlinedFun (wayland-client.c:1591)                                                                                           
==16261==    by 0x4A4A19B: wl_display_dispatch_queue_pending (wayland-client.c:1833)
==16261==  Address 0x589b4d0 is 288 bytes inside a block of size 360 free'd                                                                                    
==16261==    at 0x483A9F5: free (vg_replace_malloc.c:538)                                                                                                      
==16261==    by 0x5461B0F: ffi_call_unix64 (unix64.S:76)                                                                                                       
==16261==    by 0x54610A2: ffi_call (ffi64.c:525)                                                                                                              
==16261==    by 0x4A498FD: wl_closure_invoke.constprop.0 (connection.c:1018)                                                                                   
==16261==    by 0x4A49FCA: dispatch_event.isra.0 (wayland-client.c:1445)                                                                                       
==16261==    by 0x4A4A19B: UnknownInlinedFun (wayland-client.c:1591)                                                                                           
==16261==    by 0x4A4A19B: wl_display_dispatch_queue_pending (wayland-client.c:1833)
==16261==    by 0x111943: display_in (main.c:1080)                             
==16261==    by 0x10E8A5: UnknownInlinedFun (loop.c:95)                                                                                                        
==16261==    by 0x10E8A5: main (main.c:1235)                                   
==16261==  Block was alloc'd at                                                
==16261==    at 0x483BAE9: calloc (vg_replace_malloc.c:760)                                                                                                    
==16261==    by 0x11059E: UnknownInlinedFun (main.c:333)                                                                                                       
==16261==    by 0x11059E: handle_global (main.c:303)                           
==16261==    by 0x5461B0F: ffi_call_unix64 (unix64.S:76)                                                                                                       
==16261==    by 0x54610A2: ffi_call (ffi64.c:525)                              
==16261==    by 0x4A498FD: wl_closure_invoke.constprop.0 (connection.c:1018)                                                                                   
==16261==    by 0x4A49FCA: dispatch_event.isra.0 (wayland-client.c:1445)                                                                                       
==16261==    by 0x4A4A19B: UnknownInlinedFun (wayland-client.c:1591)                                                                                           
==16261==    by 0x4A4A19B: wl_display_dispatch_queue_pending (wayland-client.c:1833)
==16261==    by 0x4A4C6EE: wl_display_roundtrip_queue (wayland-client.c:1251)                                                                                  
==16261==    by 0x10E650: main (main.c:1182)                                   
==16261==                              
==16369== Warning: invalid file descriptor 1024 in syscall close()  
```

**Comment by rfs613** [comment]
Thanks to a suggestion on IRC, have applied 235b925df7e1bb82d98f1ac8c02e8f85d0a54ee9
This seems to have resolved the issue.
